// src/pages/AdminProduct.jsx
import React, { useState } from 'react';
import { userRequest } from '../requestMethods';
import { toast } from 'react-toastify';
import { useNavigate } from 'react-router-dom';

const AdminProduct = () => {
  const [name, setName] = useState("");
  const [description, setDescription] = useState("");
  const [price, setPrice] = useState("");
  const [category, setCategory] = useState("");
  const [image, setImage] = useState("");
  const [stock, setStock] = useState("");
  const [loadingAI, setLoadingAI] = useState(false);
  
  const navigate = useNavigate();

  // --- THE AI MAGIC ---
  const handleGenerateAI = async (e) => {
    e.preventDefault();
    if (!name) return toast.warning("Please enter a product name first!");
    
    setLoadingAI(true);
    try {
      const res = await userRequest.post("/ai/generate", { productName: name });
      // The AI response is in res.data.description
      setDescription(res.data.description);
      toast.success("Description generated by AI! ✨");
    } catch (err) {
      console.error(err);
      toast.error("AI Generation failed. Check console.");
    } finally {
      setLoadingAI(false);
    }
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    try {
      await userRequest.post("/products", {
        name,
        description,
        price: Number(price),
        category,
        image,
        stock: Number(stock)
      });
      toast.success("Product Created Successfully!");
      navigate("/"); // Go back to shop
    } catch (err) {
        console.error(err);
        toast.error("Failed to create product. Are you an Admin?");
    }
  };

  return (
    <div className="flex items-center justify-center min-h-screen bg-gray-100 p-5">
      <div className="w-full max-w-lg p-8 space-y-6 bg-white rounded-xl shadow-lg">
        <h2 className="text-3xl font-bold text-center text-gray-800">Add New Product</h2>
        
        <form className="space-y-5" onSubmit={handleSubmit}>
          
          {/* Product Name */}
          <div>
              <label className="block text-sm font-medium text-gray-700">Product Name</label>
              <input 
                className="w-full p-3 border rounded-lg mt-1 focus:ring-2 focus:ring-blue-500 outline-none" 
                placeholder="e.g. Neon Cyberpunk Hoodie" 
                onChange={(e) => setName(e.target.value)} 
                required 
              />
          </div>
          
          {/* AI Description Box */}
          <div className="relative">
            <label className="block text-sm font-medium text-gray-700">Description</label>
            <textarea 
              className="w-full p-3 border rounded-lg h-32 mt-1 focus:ring-2 focus:ring-blue-500 outline-none resize-none" 
              placeholder="Enter description or generate with AI..." 
              value={description}
              onChange={(e) => setDescription(e.target.value)}
              required 
            />
            <button 
              onClick={handleGenerateAI}
              disabled={loadingAI}
              type="button" // Important: prevents form submission
              className="absolute bottom-3 right-3 bg-purple-600 text-white text-xs px-3 py-1 rounded-full hover:bg-purple-700 transition disabled:bg-purple-300 flex items-center gap-1 shadow-sm"
            >
              {loadingAI ? (
                  <>Thinking...</>
              ) : (
                  <>✨ Generate with AI</>
              )}
            </button>
          </div>

          {/* Price & Stock Row */}
          <div className="flex gap-4">
              <div className="flex-1">
                <label className="block text-sm font-medium text-gray-700">Price ($)</label>
                <input 
                    className="w-full p-3 border rounded-lg mt-1" 
                    type="number" 
                    placeholder="29.99" 
                    onChange={(e) => setPrice(e.target.value)} 
                    required 
                />
              </div>
              <div className="flex-1">
                <label className="block text-sm font-medium text-gray-700">Stock</label>
                <input 
                    className="w-full p-3 border rounded-lg mt-1" 
                    type="number" 
                    placeholder="100" 
                    onChange={(e) => setStock(e.target.value)} 
                    required 
                />
              </div>
          </div>

          {/* Category */}
          <div>
              <label className="block text-sm font-medium text-gray-700">Category</label>
              <input 
                className="w-full p-3 border rounded-lg mt-1" 
                placeholder="e.g. Men, Shoes" 
                onChange={(e) => setCategory(e.target.value)} 
                required 
              />
          </div>

          {/* Image URL */}
          <div>
              <label className="block text-sm font-medium text-gray-700">Image URL</label>
              <input 
                className="w-full p-3 border rounded-lg mt-1" 
                placeholder="https://..." 
                onChange={(e) => setImage(e.target.value)} 
                required 
              />
          </div>

          <button 
            type="submit" 
            className="w-full p-3 text-white bg-black rounded-lg font-bold hover:bg-gray-800 transition shadow-md transform active:scale-95"
          >
            CREATE PRODUCT
          </button>
        </form>
      </div>
    </div>
  );
};

export default AdminProduct;